NHSDigital/nhs-website-content-api

specification/nhs-website-content-api.yaml
=> Alpha content review

proxies/live/apiproxy/policies/javascript.CaptureProxyHostName.xml, proxies/live/apiproxy/policies/javascript.rewriteHostName.xml, specification/nhs-website-content-api.yaml
=> Deploy Test - demo

azure/azure-release-pipeline.yml
=> Remove test=param

azure/azure-release-pipeline.yml
=> int deployment using smoketest

azure/azure-release-pipeline.yml, tests/test_endpoints.py
=> Skipped smoke test

openapitools.json, package-lock.json, specification/nhs-website-content-api.yaml
=> Updated spec document

package-lock.json, package.json
=> Change CLI generator

azure/project.yml
=> Changes service_base_path

azure/azure-release-pipeline.yml
=> fixed sandbox dependecy order

azure/azure-release-pipeline.yml
=> Changed dev sandbox name

azure/azure-release-pipeline.yml
=> Changed sandbox dependency

specification/nhs-website-content-api.yaml, specification/postman-collection.json
=> Added a Postman collection to the spec

specification/nhs-website-content-api.yaml
=> Spec update

manifest_template.yml
=> Set rate limit per env

manifest_template.yml
=> Added a description

tests/test_endpoints.py
=> Stop running test in prod

manifest_template.yml
=> Rate limits

specification/nhs-website-content-api.yaml
=> Update spec document

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> Added wildcard to cors header

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> Added ‘apikey’ to the "Access-Control-Allow-Headers"

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> Added Access-Control-Allow-Origin to exposed headers

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> Updated headers

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> Removed Access-Control-Expose-Headers

specification/nhs-website-content-api.yaml
=> SYN-733: Using ‘nhsuk-details’ component

specification/nhs-website-content-api.yaml
=> SYN-733: Add a list of the sandbox endpoints to the spec (CSS tweak)

manifest_template.yml
=> Updated the ‘PRODUCT_DISPLAY_NAME’ to be ‘NHS Website Content API’

proxies/live/apiproxy/resources/jsc/SearchAndReplaceResponse.js, proxies/sandbox/apiproxy/resources/jsc/SearchAndReplaceResponse.js, pyproject.toml
=> SYN-732: Point 'url' to website page (not the API endpoint)

proxies/live/apiproxy/resources/jsc/SearchAndReplaceResponse.js, proxies/sandbox/apiproxy/resources/jsc/SearchAndReplaceResponse.js
=> Check if “url” property is at the root or inside the “about” object

specification/components/examples/CommonHealthQuestionsContentPage.json, specification/components/examples/CommonHealthQuestionsHubPage.json, specification/components/examples/ConditionsContentPage.json, specification/components/examples/ConditionsHealthAToZ.json, specification/components/examples/LiveWellContentPage.json, specification/components/examples/LiveWellHubPage.json, specification/components/examples/MedicinesAToZ.json, specification/components/examples/MedicinesContentPage.json, specification/components/examples/MentalHealthContentPage.json, specification/components/examples/MentalHealthHubPage.json, specification/components/examples/NhsServicesContentPage.json, specification/components/examples/NhsServicesHubPage.json, specification/components/examples/PregnancyContentPage.json, specification/components/examples/PregnancyHubPage.json, specification/components/schemas/WebPage.json
=> SYN-745: Add the "webpage" property to the examples and schema in the spec doc

proxies/live/apiproxy/resources/jsc/SearchAndReplaceResponse.js, proxies/sandbox/apiproxy/resources/jsc/SearchAndReplaceResponse.js
=> Commented out the Search and Replace in Sandbox

specification/nhs-website-content-api.yaml
=> SYN-755: Fixed dodgy characters

sandbox/app.js
=> SYN-758: Removed ‘/health’ endpoint from Sandbox

azure/azure-release-pipeline.yml, tests/test_endpoints.py
=> Skip smoketest

manifest_template.yml
=> internal-dev ratelimit: 1pm # 1 request per minute

manifest_template.yml
The commit corrects the environment variable references in the quota and ratelimit sections of the manifest_template.yml file. These changes ensure that the correct values are being fetched for limit and ratelimit parameters, increasing the accuracy and integrity of the referencing system.
=> Update variable references in manifest_template.yml

manifest_template.yml
This commit updates the values of 'ratelimit' and 'quota' for different environments in the manifest_template.yml file. The changes are aimed at correctly configuring the request limits for each environment, thus improving the system's performance and reliability.
=> Adjust ratelimit and quota in manifest_template.yml

manifest_template.yml
=> Finalising Rate Limits

specification/nhs-website-content-api.yaml
=> Documentation: 600 requests per minute

.gitignore
The .idea/ directory, which typically holds IDE settings, was previously ignored. Now, it has been included in .gitignore to enable tracking. This adjustment will aid in preserving uniform development environments across multiple systems.
=> Update .gitignore to include .idea/ directory

specification/nhs-website-content-api.yaml
=> Added Developer Community text

specification/nhs-website-content-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/SYN-773
=> SYN-773: Spec documentation updates

specification/nhs-website-content-api.yaml
=> SYN-774: Updated the ‘Security and authorisation’ text

specification/nhs-website-content-api.yaml
=> Updated text

README.md, proxies/live/apiproxy/policies/KeyValueMapOperations.GetSubscriptionKey.xml, proxies/live/apiproxy/targets/target.xml
=> Added a full stop at the end of the README file

specification/nhs-website-content-api.yaml
=> SYN-847: Added deep link to the Developer Community

proxies/live/apiproxy/policies/FlowCallout.EnhancedVerifyApiKey.xml, proxies/live/apiproxy/policies/VerifyApiKey.FromHeader.xml, proxies/live/apiproxy/targets/target.xml
=> APM-5277 Use enhanced verify api key

specification/nhs-website-content-api.yaml
=> SYN-777: Documentation - Add information about "Modularised NHS content"

specification/nhs-website-content-api.yaml
=> Text changes

proxies/live/apiproxy/resources/jsc/SearchAndReplaceResponse.js
=> Added search and replace Regex for ‘vaccinations’ and ‘contraception’

proxies/live/apiproxy/resources/jsc/SearchAndReplaceResponse.js
=> SYN-904: Updated Search and Replace to include manifest pages JSON

specification/nhs-website-content-api.yaml
=> Removed references to query param ‘childArticles’

specification/components/examples/ManifestPages.json, specification/components/schemas/ManifestPages.json, specification/nhs-website-content-api.yaml
=> SYN-916 - Add manifest pages documentation

package.json
=> SYN-926 - Update package.json details

specification/nhs-website-content-api.yaml
=> SYN-765: Attribution Logo Missing

proxies/live/apiproxy/resources/jsc/SearchAndReplaceResponse.js, proxies/sandbox/apiproxy/resources/jsc/SearchAndReplaceResponse.js
=> SYN-958: Convert any remaining relative HREFs to absolute HREFs

specification/nhs-website-content-api.yaml
=> SYN-961 - Remove full stops

proxies/live/apiproxy/resources/jsc/SearchAndReplaceResponse.js
=> Update search and replace regex patterns for NHS website non prod links
